[package]
authors 		= ['Octopus Network <hi@oct.network>']
edition 		= '2021'
name 			= 'pallet-ibc'
version 		= "3.0.0-pre.0"
license 		= "Apache-2.0"
homepage 		= "https://oct.network"
repository 		= "https://github.com/octopus-network/substrate-ibc/"
description 	= "An IBC implementation on Substrate."
readme 			= "README.md"
build       	= 'build.rs'
documentation 	= "https://docs.rs/pallet-ibc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies.substrate-wasm-builder]
branch = 'polkadot-v0.9.12'
git    = 'https://github.com/paritytech/substrate.git'

[dependencies]
codec 					= { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log 					= { version = "0.4.0", default-features = false }
scale-info 				= { version = "1.0", default-features = false, features = ["derive"] }

frame-benchmarking 		= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false, optional = true }
frame-support 			= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
frame-system 			= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-core 				= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-runtime 				= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-std 					= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-io 					= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
prost-types 			= { version = "0.9.0", default-features = false }

# ibc 					= { git = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/integer-update-client-state-to-start-command", default-features = false }
 ibc 					= { path = "../ibc-rs/modules", default-features = false }
beefy-light-client = 	{ git = "https://github.com/octopus-network/beefy-light-client.git", default-features = false }
serde_json 				= { version = "1.0", default-features = false }

[dependencies.tendermint-proto]
version = "=0.23.5"
default-features = false

[dev-dependencies]
hex 		= '0.4.0'
sha2 		= '0.9.3'
serde 	    = { version = "1.0" }
# ibc 		= { git = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/integer-update-client-state-to-start-command", features = ["mocks"]}
 ibc 		= { path = "../ibc-rs/modules" }
sp-io 		= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12"}
sp-runtime 	= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }
sp-std 		= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }
sp-keyring 	= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }
chrono = "0.4.19"



[features]
default = ['std']
std = [
	'codec/std',
	'log/std',
	"scale-info/std",
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-core/std',
	'sp-std/std',
	'ibc/std',
	'prost-types/std',
	'beefy-light-client/std',
	'serde_json/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]

[patch.crates-io]
# for tendermint
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
